networks:

  frontend-backend:
    driver: bridge
  backend-database:
    driver: bridge
  database:
    driver: bridge

volumes:

  backend:
  frontend:
  database:

services:

  frontend:

    container_name: frontend-dev
    build: ./svelte/
    volumes:
      - ./svelte/:/app
    depends_on:
      - backend
    networks:
      - frontend-backend
    ports:
      - "5173:5173"
    restart: on-failure

  backend:

    container_name: backend-dev
    build: ./symfony/
    volumes:
      - ./symfony/:/app
    depends_on:
      - database
    networks:
      - frontend-backend
      - backend-database
    ports:
      - "8000:8000"
    restart: on-failure

  database:

    container_name: database-dev
    build: ./postgres/
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - backend-database
      - database
    ports:
      - "5432:5432"
    restart: on-failure

  pgadmin:

    container_name: pgadmin-dev
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_SERVER_JSON_FILE: '/pgadmin4/servers.json'
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    networks:
      - database
    ports:
      - "9000:80"
    restart: on-failure
