networks:

  network:
    driver: bridge
  
volumes:

  backend:
  frontend:
  database:

services:

  frontend:

    container_name: frontend-development
    build: ./frontend/dev/
    env_file:
      - ./frontend/dev/.env
    depends_on:
      - backend
    networks:
      - network
    ports:
      - "7000:5173"
    restart: on-failure

  backend:

    container_name: backend-development
    build: ./backend/dev/
    env_file:
      - ./backend/dev/.env
    depends_on:
      - database
    networks:
      - network
    ports:
      - "8000:8000"
    restart: on-failure

  database:

    container_name: database-development
    build: ./database/dev/
    env_file:
      - ./database/dev/.env
    networks:
      - network
    ports:
      - "9000:5432"
    restart: on-failure