networks:

  network:
    driver: bridge
  
volumes:

  backend:
  frontend:
  database:

services:

  frontend:

    container_name: frontend-dev
    build: ./frontend/dev/
    env_file:
      - ./frontend/dev/.env
    volumes:
      - ./frontend/dev/svelte/:/app
    depends_on:
      - backend
    networks:
      - network
    ports:
      - "7000:5173"
    restart: on-failure

  backend:

    container_name: backend-dev
    build: ./backend/dev/
    env_file:
      - ./backend/dev/.env
    volumes:
      - ./backend/dev/symfony:/app
    depends_on:
      - database
    networks:
      - network
    ports:
      - "8000:8000"
    restart: on-failure

  database:

    container_name: database-dev
    build: ./database/dev/
    env_file:
      - ./database/dev/.env
    networks:
      - network
    ports:
      - "5432:5432"
    restart: on-failure

  pgadmin:

    container_name: pgadmin-dev
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    networks:
      - network
    ports:
      - "9000:80"
    restart: on-failure
